# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module MyCalculator
  class OperationEnum
    # TODO: Write general description for SUM
    # TODO: Write general description for SUBTRACT
    # TODO: Write general description for MULTIPLY
    # TODO: Write general description for DIVIDE
    OPERATION_ENUM = [SUM = 'SUM', SUBTRACT = 'SUBTRACT', MULTIPLY = 'MULTIPLY', DIVIDE = 'DIVIDE']
  end
end