# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module MyCalculator
  class MyCalculatorClient
    # Singleton access to operation controller
    # @return [OperationController] Returns the controller instance
    def operation
      OperationController.instance
    end

  end
end
